---
- name: InstallIng Iptables
  apt: 
    pkg: 
      - iptables
      - iptables-persistent
    state: latest
    install_recommends: yes      

- name: Allow tcp flags
  iptables:
    action: insert
    table: filter 
    protocol: tcp
    ctstate: ESTABLISHED,RELATED
    chain: INPUT
    jump: ACCEPT
    rule_num: 1

- name: Allow ssh
  iptables: 
    action: insert
    table: filter
    protocol: tcp
    destination_port: 22
    chain: INPUT
    jump: ACCEPT
    rule_num: 2

- name: Allow custom
  iptables:
    action: insert
    table: filter
    protocol: tcp
    destination_port: "{{ app_port }}"
    chain: INPUT
    jump: ACCEPT
    rule_num: 3

- name: Allow dns
  iptables:
    action: insert
    table: filter
    protocol: udp
    destination_port: 53
    chain: INPUT
    jump: ACCEPT
    rule_num: 4

- name: Allow dns 2
  iptables:
    action: insert
    table: filter
    protocol: udp
    source_port: 53
    chain: INPUT
    jump: ACCEPT
    rule_num: 5

- name: Block others
  iptables:
    action: append
    table: filter
    chain: INPUT
    jump: DROP
    
- name: Creating Folder
  file: 
    path: "/etc/iptables"
    mode: 0755
    state: directory

- name: Save iptables
  shell: /sbin/iptables-save > /etc/iptables/rules.v4



   
