--- 

- name: Add specified repository
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: u+rw,g+r,o-rwx

- name: InstallIng Git and VirtualEnv
  apt: 
    pkg: 
      - git
      - virtualenv   
      - python3-pip 
      - python3-venv  
      - libssl-dev
    state: latest
    install_recommends: yes    

- name: Creating Project Folder
  file: 
    path: "{{ source_folder }}"
    mode: 0755
    state: directory

- import_tasks: pippackages.yml 

- name: Clone Repo
  git:
    repo: 'https://{{ gitlab_username | urlencode }}:{{ gitlab_password | urlencode }}@github.com/Kromelky/FlaskApplication.git'
    clone: yes
    dest: '{{source_folder}}/service'
    force: yes
    
- name: Copy key
  copy:
    src: key.pem 
    dest: '{{ source_folder }}/service/cert/key.pem'
    mode: 0644

- name: Copy cert
  copy:
    src: cert.pem 
    dest: '{{ source_folder }}/service/cert/cert.pem'
    mode: 0644

- name: Make run file
  copy:
    content: |
      #! /bin/sh
      {{ venv }}/bin/python {{ source_folder }}/service/main.py
    dest: '{{ source_folder }}/service/run.sh'
  
- name: Make service file
  template:
    src: awesomezoo.j2
    dest: '{{source_folder}}/service/awesomezoo.service'

- name: Add executable
  file:
    path: '{{source_folder}}'
    mode: 0775
    group: '{{ ansible_ssh_user }}'
    recurse: yes

- name: Create symbolic link 
  file:
    src: '{{source_folder}}/service/awesomezoo.service'
    dest: "/etc/systemd/system/awesomezoo.service"
    state: link
  notify: 
    - Reload daemons
    - Restart Rest service

- name: Enable Rest service
  service: 
    name: awesomezoo
    enabled: yes

- name: Modify host for subdoman
  lineinfile:
    insertafter : '^127\.0\.0\.1\s+localhost$'
    path: /etc/hosts
    line: '{{ ansible_host }} {{ ansible_nodename }}.localhost'    

- import_tasks: iptables.yml 

- name: Push key
  authorized_key:
    user: '{{ ansible_ssh_user }}'
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
    manage_dir: True

- name: Enable PubkeyAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication*'
    line: 'PubkeyAuthentication yes'
  notify: restart ssh

- name: Disable chalange auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication '
    line: 'ChallengeResponseAuthentication no'
  notify: restart ssh

- name: Disable password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    line: 'PasswordAuthentication no'
  notify: restart ssh

- name: Disable UsePAM 
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM '
    line: 'UsePAM no'
  notify: restart ssh

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin '
    line: 'PermitRootLogin no'
  notify: restart ssh






  


        
