---
- name: Prepare application venv
  command: 
    cmd:  python3 -m venv {{ venv }} 
    chdir: '{{source_folder}}'

- name: upgrade pip  
  command: 
    cmd: '{{ venv }}/bin/pip install --upgrade pip'   
  ignore_errors: yes

- name: Install Flask
  pip: 
    name: Flask
    virtualenv: '{{ venv }}'
    virtualenv_python: python3.9
    chdir: '{{ venv }}/bin'

- name: Install BS4
  pip: 
    name: beautifulsoup4
    virtualenv: '{{ venv }}'
    virtualenv_python: python3.9
    chdir: '{{ venv }}/bin'

- name: Install requests
  pip: 
    name: requests
    virtualenv: '{{ venv }}'
    chdir: '{{ venv }}/bin'

- name: Install requests lxml
  pip: 
    name: lxml
    virtualenv: '{{ venv }}'
    chdir: '{{ venv }}/bin'

- name: Install PyOpenSSL out of venv
  pip: 
    name:
        - cryptography
        - pyOpenSSL



