---
- name: Prepare application venv
  command: 
    cmd:  python3 -m venv FlaskAppEnv 
    chdir: '{{source_folder}}'

- name: upgrade pip  
  command: 
    cmd: '{{ venv }}/bin/pip install --upgrade pip'
    chdir: '{{ venv }}/bin'
  ignore_errors: yes

- name: Install openssl  
  command: 
    cmd: '{{ venv }}/bin/pip install pyopenssl'
    chdir: '{{ venv }}/bin'

- name: Install Flask
  command: 
    cmd: '{{ venv }}/bin/pip install Flask'
    chdir: '{{ venv }}/bin'

- name: Install BS4
  command: 
    cmd: '{{ venv }}/bin/pip install beautifulsoup4'
    chdir: '{{ venv }}/bin'

- name: Install requests
  command: 
    cmd: '{{ venv }}/bin/pip install requests'
    chdir: '{{ venv }}/bin'

- name: Install requests lxml
  command: 
    cmd: '{{ venv }}/bin/pip install lxml'
    chdir: '{{ venv }}/bin'



