---
  - name: Reload daemons
    command: systemctl daemon-reload

  - name: Restart Rest service
    service: 
      name: awesomezoo
      state: started

  - name: restart ssh
    service:
      name: sshd
      state: restarted
  
  - name: reload bashrc
    command: . .bashrc